name: ElementumLabs
favicon: null
layout_spectrum: 0
typography_spectrum: 0.10874461685307324
title: ElementumLabs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-79750093-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#9f9f9f'
    - '#d8d8d8'
    - '#4a4a4a'
  brandStrength: 0.7487287661060691
  lightness: 0.42017244384624064
  saturation: 0.7992505680304021
  rhythmicContrast: 0.41481588617898524
purpose: []
