name: ElementumLabs
favicon: null
layout_spectrum: 0.9899046018254012
typography_spectrum: 0.10874461685307324
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-79750093-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7487287661060691
  lightness: 0.42017244384624064
  saturation: 0.7992505680304021
  rhythmicContrast: 0.41481588617898524
purpose: []
